### ISSUE TITLE
xray::distribution on character vector with thousands of unique values

### ISSUE THREAD

**Issue by bbrewington** [sicarul/xray#1]
I ran xray::distributions on a data frame with a couple columns, address (3185 unique values) and cfsm (4558 unique values), and it overwhelmed the plotting device.  Maybe build in a way to only pick the top N elements by occurance, and lump the rest together into "other"?  Or skip the variable altogether.

![xray_distributions_issue](https://user-images.githubusercontent.com/10573749/33109593-7272232a-cf10-11e7-986d-f8b265a2d8e6.png)

**Comment by sicarul** [comment]
I thought i handled that case :man_facepalming: thanks for the report, i'll fix it.

**Comment by sicarul** [comment]
Fixed with Commit c67e34bdb19abc206881644eb2ba9610ee71173b
I'll close the ticket now, let me know if you find any more bugs :bug: 

Thanks!

**Comment by bbrewington** [comment]
Awesome, and will do.  I REALLY like this package.  Pretty simple, but automates some essential data quality processes and I'll be using it all the time.  Wonder if this will make it into the tidyverse :)
