### ISSUE TITLE
Add more options for timebased argument time_unit

### ISSUE THREAD

**Issue by bbrewington** [sicarul/xray#10]
Currently, the options are year, month, hour, minute, and second...source: https://github.com/sicarul/xray/blob/ed269cd470cdd4e23824dd9a164f6bfc4927a2be/R/timebased.R#L65-L71

Week is a key option that's missing, and for business folks quarter might be good as well.

Here are the options that lubridate::floor_date support:
second, minute, hour, day, week, month, bimonth, quarter, season, halfyear

**Comment by sicarul** [comment]
Those are the automatic options, there is a parameter to choose any time unit named `time_unit`, for automatic choosing i don't think we  should choose those other units. All those options you mentioned should work if chosen as the parameter.

**Comment by sicarul** [comment]
I'll close this issue for now, feel free to reopen if you were meaning something else.
