### ISSUE TITLE
Xray = great pkg. Issue with unreadable values in x-axis of all bar charts (Distributions)

### ISSUE THREAD

**Issue by sfd99** [sicarul/xray#7]
**_Hi Pablo,_**

xray pkg = _very useful!_

I did:
   distributions(mtcars)

Everything shows ok,
but the **_bar charts_** (ie: for carb, am, vs...),
_do not show_ any (visible) label values **along the** **x-axis**.

Only very tiny unknown symbols appear as x-axis labels
of all bar charts, instead of 0 and 1 for the am variable.
(even if I _zoom_ the bar charts in Rstudio, 
the x-axis labels are _not readable_...).

The labels of the x-axis in all Histograms are ok.
The problem is only with the x-axis labels
in the bar charts...

Using the _latest_ version of **R** + **Rstudio**
in **Ubuntu Linux 14.04 32-bit**.
**_SFd
San Francisco_**

**Comment by sicarul** [comment]
I see them like this, can you share how you are seeing them?
Is it possible you are using an old version of ggplot2?
![image](https://user-images.githubusercontent.com/4952116/33787095-76aed1c6-dc4a-11e7-86aa-8e79a21733f9.png)

**Comment by sfd99** [comment]
**_Hi Pablo,_**

Ok!, now I finally see 
the x-axis labels of the Bar Charts (**am**, **cyl**, **vs**, **gear**, **carb**).

The number labels (ie: 4, 6, 8 for cyl)
are "tilted", inclined to the left.

**## Q:**
Anyway you could straighten these Bar Charts labels "up"
in the next version of **xray**,
just like you have in your Histograms charts x-axis labels **?**.

(all the x-axis label numbers  in Histograms
are already in a normal "up" position).  :-)

Thanks for your effort, Pablo!
Appreciated...

 **Using the latest version of R + Rstudio, ggstudio2
in Ubuntu Linux 14.04 32-bit.
SFd
San Francisco**

**Comment by sicarul** [comment]
Oh, i tilted them because when the strings are long they become unreadable, overlapping with each other. Though, we could add some logic to make it be straight when the labels are short, i'll take your feedback.

Thanks

**Comment by sicarul** [comment]
Fixed in commit 1b91ea65
